package com.indix.petstore.models

/**
 * Represents a Tag for pets. Tags cannot be passed with user-made, IDs.
 * @param id The unique, autogenerated ID of this Tag.
 * @param name The name of this Tag.
 */
case class Tag(id: Option[Long], name: String)
